apiVersion: v3
kind: service
metadata:
  name: test-harsh
  displayName: Test Harsh Service
  description: A Go-based microservice for address management and API operations
  owner: platform-team
  links:
    - name: API Documentation
      type: doc
      url: https://github.com/trafilea/test-harsh/blob/main/README.md
      provider: github
    - name: Repository
      type: repo
      url: https://github.com/trafilea/test-harsh
      provider: github
  tags:
    - env:dev
    - team:platform
    - language:go
    - type:microservice
    - domain:address-management
  contacts:
    - type: slack
      contact: "#platform-team"
    - type: email
      contact: platform-team@company.com
spec:
  lifecycle: dev
  tier: "3"
  type: web
  languages:
    - go

---

apiVersion: v3
kind: api
metadata:
  name: address-api
  displayName: Address Management API
  description: RESTful API for managing customer addresses with validation and geocoding
  owner: platform-team
  links:
    - name: API Documentation
      type: doc
      url: https://github.com/trafilea/test-harsh/blob/main/README.md
      provider: github
    - name: Repository
      type: repo
      url: https://github.com/trafilea/test-harsh
      provider: github
  tags:
    - env:dev
    - team:platform
    - api-version:v1
    - protocol:rest
    - domain:address-management
  contacts:
    - type: slack
      name: Platform Team Slack
      contact: "#platform-team"
    - type: email
      name: Platform Team Email
      contact: platform-team@company.com
spec:
  interface:
    fileRef: "https://github.com/trafilea/test-harsh/blob/main/address.yml"
  lifecycle: dev
  tier: high
  type: REST
  implementedBy:
    - service:test-harsh
