apiVersion: v3
kind: service
metadata:
  name: test-harsh
spec:
  lifecycle: dev

---

apiVersion: v3
kind: api
metadata:
  name: test-harsh
  displayName: Address API
  owner: platform-team
  repository: https://github.com/trafilea/test-harsh
spec:
  lifecycle: dev
  definition:
    type: openapi
    url: https://github.com/trafilea/test-harsh/main/address.yml
